# LetsEncrypt tasks - nginx.yml
---
- name: install required packages - letsencrypt-nginx
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - python-certbot-nginx

- name: create letsencrypt cert
  shell: "certbot --nginx certonly --agree-tos --quiet -m {{ letsencrypt_email }} -d {{ letsencrypt_domain_name }}"
  when: (ansible_local['letsencrypt']['certificates'][letsencrypt_domain_name] is undefined) or
        (ansible_local['letsencrypt']['certificates'][letsencrypt_domain_name]['valid_days'] < 15)
  register: create_letsencrypt_cert

- name: re-check local facts
  setup:
    fact_path: /etc/ansible/facts.d
    filter: ansible_local*
  when: create_letsencrypt_cert.changed

- name: create ssl config file
  template:
    src: ssl.conf.j2
    dest: "/etc/nginx/snippets//ssl-{{ letsencrypt_domain_name }}.conf"
    owner: root
    group: root
    mode: 0644

- name: copy nginx ssl-params config file
  copy:
    src: ssl-nginx-params.conf
    dest: /etc/nginx/snippets/ssl-nginx-params.conf
    owner: root
    group: root
    mode: 0644
