# MunkiReport tasks - nginx.yml
---
- name: apply nginx sites-available template
  template:
    src: "{{ ansible_local.munkireport.ssl.sites_available }}sites-available.munkireport.j2"
    dest: /etc/nginx/sites-available/munkireport
    owner: root
    group: root
    mode: 0644
  register: munkireport_sites_available
  notify:
    - restart nginx

- name: add munkireport to nginx sites-enabled
  file:
    src: /etc/nginx/sites-available/munkireport
    dest: /etc/nginx/sites-enabled/munkireport
    state: link
  notify:
    - restart nginx
    - restart php7

- name: modify nginx config file
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '.*default_type application/octet-stream;'
    line: '#default_type application/octet-stream;'
  notify:
    - restart nginx