# Common tasks - main.yml
---
- name: update packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade packages
  apt:
    upgrade: yes
    autoremove: yes
  when: upgrade_packages

- name: install required packages - common
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - aptitude
    - fail2ban
    - openssh-server
    - python
    - python-apt
    - python-pip
    - python3
    - python3-apt
