# Snipe-IT tasks - nginx.yml
---
- name: apply nginx sites-available template
  template:
    src: "{{ ansible_local.snipeit.security.ssl }}.sites-available.snipeit.j2"
    dest: /etc/nginx/sites-available/snipe-it
    owner: root
    group: root
    mode: 0644
  register: snipeit_sites_available
  notify:
    - restart nginx
    - restart php7

- name: add snipe-it to nginx sites-enabled
  file:
    src: /etc/nginx/sites-available/snipe-it
    dest: /etc/nginx/sites-enabled/snipe-it
    state: link
  notify:
    - restart nginx
    - restart php7