# Munki tasks - main.yml
---
- name: create munki group
  group:
    name: munki
    system: yes

- name: create munki user
  user:
    name: munki
    comment: "Munki User"
    group: munki
    shell: /bin/bash
    system: yes

- name: add web user (www-data) to munki group
  user:
    name: www-data
    group: munki

- name: install required packages - munki
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2-utils
    - build-essential
    - curl
    - git
    - python-passlib

- name: include facts tasks
  include: facts.yml

- name: include nginx tasks
  include: nginx.yml

- name: create munki repo mount point
  file:
    path: /srv/munki-repo
    state: directory
    owner: root
    group: munki
    mode: 02744

- name: symlink to munki repo
  file:
    src: /srv/munki-repo
    dest: /usr/share/nginx/html/munki-repo
    state: link

- name: include mount tasks
  include: mount.yml
  when:
    - munki_mount_fstype is defined
    - munki_repo_share is defined
  register: mount_munki_repo

- name: include host tasks
  include: host.yml
  when:
    - mount_munki_repo|skipped
    - munki_samba_password is defined

- name: ensure web services are running
  service:
    name: nginx
    state: started