# Munki tasks - mount.yml
---
- name: install required packages - mount munki repo (cifs)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - cifs-utils
  when: munki_mount_fstype == "cifs" or munki_mount_fstype == "smb"

- name: install required packages - mount munki repo (nfs)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nfs-common
  when: munki_mount_fstype == "nfs"

- name:  create munki mount credentials
  template:
    src: munki_mount_credentials.j2
    dest: /root/.munki_mount_credentials
    owner: root
    group: root
    mode: 0600

- name: mount munki repo share (cifs)
  mount:
    path: /srv/munki-repo
    src: "{{ munki_repo_share }}"
    fstype: cifs
    opts: "credentials=/root/.munki_mount_credentials,{{ munki_mount_options }}"
    state: mounted
  when: munki_mount_fstype == "cifs" or munki_mount_fstype == "smb"

- name: mount munki repo share (nfs)
  mount:
    path: /srv/munki-repo
    src: "{{ munki_repo_share }}"
    fstype: nfs
    opts: "{{ munki_mount_options }}"
    state: mounted
  when: munki_mount_fstype == "nfs"

- name: mount munki repo share (other)
  mount:
    path: /srv/munki-repo
    src: "{{ munki_repo_share }}"
    fstype: "{{ munki_mount_fstype }}"
    opts: "{{ munki_mount_options }}"
    state: mounted
  when:
    - munki_mount_fstype != "cifs"
    - munki_mount_fstype != "smb"
    - munki_mount_fstype != "nfs"